weights: yolov5x6.pt
cfg: ''
data: dataset.yaml
hyp: hyp.finetune.yaml
epochs: 200
batch_size: 60
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: act-learning-panel-data
entity: null
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
freeze: 0
